--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/harsh/.livewallpaper/mpv-shot0001.jpg"

-- Special
background="#0c091b"
foreground="#a2c2db"
cursor="#a2c2db"

-- Colors
color0="#0c091b"
color1="#295969"
color2="#535F70"
color3="#9F7774"
color4="#2C6B9C"
color5="#4B729F"
color6="#3589E2"
color7="#a2c2db"
color8="#718799"
color9="#295969"
color10="#535F70"
color11="#9F7774"
color12="#2C6B9C"
color13="#4B729F"
color14="#3589E2"
color15="#a2c2db"
