# Shell variables
# Generated by 'wal'
wallpaper='/home/harsh/.livewallpaper/mpv-shot0001.jpg'

# Special
background='#0c091b'
foreground='#a2c2db'
cursor='#a2c2db'

# Colors
color0='#0c091b'
color1='#295969'
color2='#535F70'
color3='#9F7774'
color4='#2C6B9C'
color5='#4B729F'
color6='#3589E2'
color7='#a2c2db'
color8='#718799'
color9='#295969'
color10='#535F70'
color11='#9F7774'
color12='#2C6B9C'
color13='#4B729F'
color14='#3589E2'
color15='#a2c2db'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
