#! /bin/sh

FILE="$(fzf)"

programe="$(printf "vim\nsxiv\nmpv" | dmenu)"

if [[ $programe = vim ]] ; then
    vim "$FILE"

elif [[ $programe = sxiv ]] ; then
    sxiv "$FILE"

elif [[ $programe = mpv ]] ; then
    mpv "$FILE"
fi
