#! /bin/sh

toggle() {
    if [ -z "$(pidof mpd)" ] ; then
        mpd
        mpdctl notify
    else
        kill "$(pidof mpd)"
    fi
}

next() {
    mpc next
}
prev() {
    mpc prev
}

pp(){
    if [ $(mpc | awk 'NR==2{print $1}') == "[playing]" ] ; then
        mpc pause
    else
        mpc play
    fi
}

notify(){
    while [ ! -z "$(pidof mpd)" ] ; do
        mpc current --wait
        pkill -RTMIN+10 dwmblocks
    done
}

case "$1" in
	toggle) toggle ;;
    pp) pp ;;
	next) next ;;
	prev) prev ;;
    notify) notify ;;

esac >/dev/null

pkill -RTMIN+10 dwmblocks
